### ISSUE TITLE
Gradle / IntelliJ not finding package 

### ISSUE THREAD

**Issue by Globegitter** [michaelbull/kotlin-inline-logger#1]
Hey, I just tried to add 
```
dependencies {
...
implementation("com.michael-bull.kotlin-inline-logger:kotlin-inline-logger:1.0.2")
...
}
```
to my build.gradle.kts because this library looks pretty good and we are already making use of your result and retry library. But when adding it, Intellij does not recognise this dependency, but it also does not show any error whatsoever. So when I try to import `import com.github.michaelbull.logging.InlineLogger` it complains about a missing `logging` package. The same for gradle when I compile the application. I can see the library in my dependencies when running `./gradlew app:dependencies` however.

I am wondering does this maybe need a specific java version / jvmTarget or gradle version to work? In this project we are using kotlin `1.3.50`, `jvmTarget` is set to `1.8` and gradle version is `5.5.1`.

**Comment by Globegitter** [comment]
@michaelbull also here just a small ping :smile:

**Comment by michaelbull** [comment]
What happens when you compile with gradle? Can you paste the full output?

Can you also paste a full snippet of a file that doesn't compile?

**Comment by Globegitter** [comment]
Ok I tried again and now it works. Very strange, I did double and triple check everything before. Well either way, I guess this can be closed :)

And thanks for all the great work!

**Comment by michaelbull** [comment]
Glad to hear it's fixed
